# Generated by Django 3.0.3 on 2020-02-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='time_units',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
